api:
  key: jCzTbBpMghoBSBPXtV4dcVJEDWZGY6qpotKwLaTw7VU3cSeBk14uXozpSYvGQ7CQSDLM9GVHyqCPhAnNuafLGg%3D%3D

# Database properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: capstone
    password: vhehdeod
    driver-class-name: com.mysql.cj.jdbc.Driver


  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
